config/routes.rb
Rails.application.routes.draw do


  rutarel = ENV.fetch('RUTA_RELATIVA', 'msip/')
 

    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      get 'salir' => 'devise/sessions#destroy',
        as: :terminar_sesion

      post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
      get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
        as: :iniciar_sesion

      # El siguiente para superar mala generación del action en el formulario
      # cuando se monta en sitio diferente a / y se autentica mal (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end

    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

    get '/casos/mapaosm' => 'sivel2_gen/casos#mapaosm'

    root 'sivel2_gen/hogar#index'
 # scope

  mount Msip::Engine, at: "/", as: 'msip'
  mount Mr519Gen::Engine, at: "/", as: 'mr519_gen'
  mount Heb412Gen::Engine, at: "/", as: 'heb412_gen'
  mount Sivel2Gen::Engine, at: "/", as: 'sivel2_gen'
  mount Cor1440Gen::Engine, at: "/", as: 'cor1440_gen'

end

app/models/ability.rb
class Ability  < Cor1440Gen::Ability

  ROLADMIN    = 1
  ROLDIR      = 3
  ROLOPERADOR = 5


  GRUPO_ANALISTA_CASOS = 20
  GRUPO_OBSERVADOR_CASOS = 21
  GRUPO_OBSERVADOR_PARTE_CASOS = 22

  ROLES = [
    ["Administrador", ROLADMIN], 
    ["", 0], 
    ["Directivo", ROLDIR], 
    ["", 0], 
    ["Operador", ROLOPERADOR],
    ["", 0 ],
    ["", 0]
  ]

  BASICAS_PROPIAS =  [
  ]
  
  def tablasbasicas 
    Msip::Ability::BASICAS_PROPIAS + 
      Heb412Gen::Ability::BASICAS_PROPIAS + 
      Cor1440Gen::Ability::BASICAS_PROPIAS +
      Sivel2Gen::Ability::BASICAS_PROPIAS + 
      BASICAS_PROPIAS
  end

  BASICAS_ID_NOAUTO = []

  def basicas_id_noauto 
    Msip::Ability::BASICAS_ID_NOAUTO +
      Heb412Gen::Ability::BASICAS_ID_NOAUTO +
      Cor1440Gen::Ability::BASICAS_ID_NOAUTO +
      Sivel2Gen::Ability::BASICAS_ID_NOAUTO +
      BASICAS_ID_NOAUTO
  end

  NOBASICAS_INDSEQID = [
  ]

  def nobasicas_indice_seq_con_id 
    Msip::Ability::NOBASICAS_INDSEQID +
      Heb412Gen::Ability::NOBASICAS_INDSEQID +
      Cor1440Gen::Ability::NOBASICAS_INDSEQID +
      Sivel2Gen::Ability::NOBASICAS_INDSEQID +
      NOBASICAS_INDSEQID
  end

  BASICAS_PRIO = []

  def tablasbasicas_prio 
    Msip::Ability::BASICAS_PRIO +
      Heb412Gen::Ability::BASICAS_PRIO +
      Sivel2Gen::Ability::BASICAS_PRIO +
      Cor1440Gen::Ability::BASICAS_PRIO +
      BASICAS_PRIO
  end

  CAMPOS_PLANTILLAS_PROPIAS = {}

    def campos_plantillas
    Heb412Gen::Ability::CAMPOS_PLANTILLAS_PROPIAS.clone.
      merge(Cor1440Gen::Ability::CAMPOS_PLANTILLAS_PROPIAS.clone).
      merge(Sivel2Gen::Ability::CAMPOS_PLANTILLAS_PROPIAS.clone).
      merge(CAMPOS_PLANTILLAS_PROPIAS.clone)
  end


  # Establece autorizaciones con CanCanCan
  # Operadores solo puede ver y editar actividades de sus proyectos, pero no
  # pueden ver ni editar casos.  Por si lo requieren a futuro, se deja grupo 
  # Analista de Casos para ver y editar casos --aunque inicialmente no tiene 
  # usuarios.
  def initialize(usuario = nil)
    Sivel2Gen::Ability.initialize_sivel2_gen(self, usuario)
    Cor1440Gen::Ability.initialize_cor1440_gen(self, usuario)

    if !usuario || !usuario.fechadeshabilitacion.nil?
      return
    end
    can :contar, Sivel2Gen::Caso
    cannot :pestanadesaparicion, Sivel2Gen::Caso

  end
end

app/models/msip/persona.rb
require 'sivel2_gen/concerns/models/persona'
require 'cor1440_gen/concerns/models/persona'

module Msip
  class Persona < ActiveRecord::Base

    SEXO_OPCIONES = [
      ['OTRO', :S], 
      ['FEMENINO', :F], 
      ['MASCULINO', :M]
    ]

    SEXO_OPCIONES_CORTAS = [
      ['O', :S], 
      ['F', :F], 
      ['M', :M]
    ]

    include Sivel2Gen::Concerns::Models::Persona
    include Cor1440Gen::Concerns::Models::Persona

  end
end

app/models/usuario.rb
require 'sivel2_gen/concerns/models/usuario'

class Usuario < ActiveRecord::Base
    include Sivel2Gen::Concerns::Models::Usuario
end

app/controllers/application_controller.rb
class ApplicationController < Msip::ApplicationController
  protect_from_forgery with: :exception

  # No define autorización porque es utilidad
  
end

app/controllers/cor1440_gen/actividades_controller.rb
require_dependency "cor1440_gen/concerns/controllers/actividades_controller"

module Cor1440Gen
  class ActividadesController < Heb412Gen::ModelosController

    include Cor1440Gen::Concerns::Controllers::ActividadesController

    before_action :set_actividad, 
      only: [:show, :edit, :update, :destroy],
      exclude: [:contar]
    load_and_authorize_resource class: Cor1440Gen::Actividad

    def edit
      edit_cor1440_gen
      @listadoasistencia = true
      render layout: 'application'
    end

  end
end

app/controllers/cor1440_gen/proyectosfinancieros_controller.rb
require_dependency "cor1440_gen/concerns/controllers/proyectosfinancieros_controller"

module Cor1440Gen
  class ProyectosfinancierosController < Heb412Gen::ModelosController
    include Cor1440Gen::Concerns::Controllers::ProyectosfinancierosController

    before_action :set_proyectofinanciero,
      only: [:show, :edit, :update, :destroy]
    skip_before_action :set_proyectofinanciero, only: [:validar]

    load_and_authorize_resource  class: Cor1440Gen::Proyectofinanciero,
      only: [:new, :create, :destroy, :edit, :update, :index, :show,
             :objetivospf]

    def atributos_index
      [ 
        :id, 
        :nombre ,
        :titulo
      ] +
      [ :financiador_ids =>  [] ] +
      [ 
        :fechainicio_localizada,
        :fechacierre_localizada,
        :responsable,
        :proyectofinanciero_usuario,
      ] +
      [ :compromisos, 
        :monto, 
        :observaciones, 
        :objetivopf,
        :indicadorobjetivo,
        :resultadopf,
        :indicadorpf,
        :actividadpf
      ]
    end


    def atributos_show
      atributos_index - [
        :objetivopf,
        :indicadorobjetivo,
        :resultadopf,
        :indicadorpf,
        :actividadpf
      ] + [ 
        :marcologico,
        :caracterizacion, 
        :beneficiario,
        :plantillahcm,
        :anexo_proyectofinanciero
      ]
    end


  end 
end

app/controllers/sivel2_gen/casos_controller.rb
# frozen_string_literal: true

require 'sivel2_gen/concerns/controllers/casos_controller'

module Sivel2Gen
  class CasosController < Heb412Gen::ModelosController

    include Sivel2Gen::Concerns::Controllers::CasosController

    before_action :set_caso, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource class: Sivel2Gen::Caso, 
      except: [:index, :show, :mapaosm, :update]

    include Sivel2Gen::Concerns::Controllers::CasosController

    def campoord_inicial
      'fecha'
    end

    # GET casos/mapa
    #def mapaosm


    #  @fechadesde = Msip::FormatoFechaHelper.inicio_semestre(Date.today - 182)
    #  @fechahasta = Msip::FormatoFechaHelper.fin_semestre(Date.today - 182)
    #  render 'mapaosm', layout: 'application'
    #end
  end
end

app/controllers/usuarios_controller.rb
require 'sivel2_gen/concerns/controllers/usuarios_controller'

class UsuariosController < Heb412Gen::ModelosController
  include Sivel2Gen::Concerns::Controllers::UsuariosController

  # No define autorización porque se requiere para autenticación
 
  def index_reordenar(c)
    if !params || !params[:filtro] || !params[:filtro][:bushabilitado]
      c = c.where("usuario.fechadeshabilitacion IS NULL")
    end
    #c = c.reorder([:apellidos])
    return c
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Sivel2Gen::ApplicationHelper 
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
  <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <% if can?(:new, Sivel2Gen::Caso) %>
        <%= despliega_abajo 'Casos' do %>
          <%= opcion_menu 'Listado', sivel2_gen.casos_path,
            desplegable: true %>
          <%= opcion_menu 'Validaciones', sivel2_gen.validarcasos_path,
            desplegable: true %>
          <%= opcion_menu 'Buscar repetidos', 
            sivel2_gen.buscarrepetidos_path, desplegable: true %>
          <%= opcion_menu 'Importar relatos XRLAT', 
            sivel2_gen.casos_importarrelatos_path, desplegable: true %>
          <%= opcion_menu 'Geolocalización de casos sobre OpenStreetMap',
            sivel2_gen.casos_mapaosm_path, desplegable: true %>
          <%= opcion_menu 'Listado de víctimas y casos', 
            sivel2_gen.victimas_path, desplegable: true %>
          <%= opcion_menu 'Conteo demografía víctimas', 
            sivel2_gen.conteos_personas_path, desplegable: true %>
          <%= opcion_menu 'Conteo general de víctimas', 
            sivel2_gen.conteos_genvic_path, desplegable: true %>
          <%= opcion_menu 'Conteo de victimizaciones individuales', 
            sivel2_gen.conteos_victimizaciones_path,
            desplegable: true %>
          <%= opcion_menu "Graficar victimizaciones individuales", 
            sivel2_gen.graficar_victimizaciones_individuales_path,
            'data-turbo' => false,
            desplegable: true %>
          <%= opcion_menu 'Mapa de victimizaciones por departamento', 
            sivel2_gen.mapadepvic_path,
            'data-turbo' => false,
            desplegable: true %>
        <% end %>
      <% end %>

      <%= despliega_abajo 'Actividades y Proyectos' do %>
        <%= opcion_menu 'Listado de Actividades', cor1440_gen.actividades_path,
          desplegable: true %>
        <%= opcion_menu 'Listado de Proyectos', 
          cor1440_gen.proyectosfinancieros_path, desplegable: true %>
        <%= opcion_menu "Conteo por actividad de marco lógico", 
          cor1440_gen.contar_actividades_path, desplegable: true %>
        <%= opcion_menu "Conteo por beneficiario y actividad de marco lógico", 
          cor1440_gen.contar_actividades_beneficiarios_path, desplegable: true %>
        <%= opcion_menu 'Medición de indicadores', 
          cor1440_gen.mindicadorespf_path, desplegable: true %>
        <%= opcion_menu 'Organizaciones Sociales', msip.orgsociales_path,
          desplegable: true %>
        <%= opcion_menu 'Participantes', 
          msip.personas_path, desplegable: true %>
      <% end %>
    <% end %>
  <% end %>

  <%= grupo_menus :pull => :right do %>
    <%= despliega_abajo 'Documentos' do %>
        <%= opcion_menu "Manual de SIVeL", 
          'https://docs.google.com/document/d/1xr1vtkfpWdpM_VrEbHacm44NiMPCzAIcRUS1ENoBrQU/edit?usp=sharing', 
          target: '_blank', desplegable: true %>
        <%= opcion_menu "Manual de Cor1440", 
          'https://docs.google.com/document/d/1mmydkqNmZbXkzcpkiegQ_XAP_NkjfX-RXgcW1yzjdpE/edit?usp=sharing', 
          target: '_blank', desplegable: true %>
        <% if !current_usuario.nil? %>
          <%= opcion_menu 'Nube', heb412_gen.sisini_path,
            desplegable: true %>
        <% end %>
      <% if can? :manage, ::Heb412Gen::Plantillahcm %>
        <%= opcion_menu 'Plantillas para listados en hojas de calculo',
          heb412_gen.plantillashcm_path, desplegable: true %>
      <% end %>
      <% if can? :manage, ::Heb412Gen::Plantillahcr %>
        <%= opcion_menu 'Plantillas para un registro en hoja de calculo',
          heb412_gen.plantillashcr_path, desplegable: true %>
      <% end %>
      <% if current_usuario.nil? %>
        <%= opcion_menu 'Acerca de', sivel2_gen.acercade_path,
          desplegable: true %>
      <% end %>
    <% end %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo 'Administrar' do %>
        <%= opcion_menu 'Clave y tema', main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if session[:capturacaso_acordeon] %>
          <%= opcion_menu 'Ficha caso vertical ✓', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' %>
        <% else %>
          <%= opcion_menu 'Ficha caso vertical', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", 
            mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Usuario %>
          <%= opcion_menu 'Usuarios', main_app.usuarios_path,
            desplegable: true %>
          <%= opcion_menu 'Respaldo cifrado', msip.respaldo7z_path,
            desplegable: true %>
          <%= opcion_menu 'Tablas Básicas', sivel2_gen.tablasbasicas_path,
            desplegable: true %>
        <% end %>
        <% if can?(:new, Sivel2Gen::Caso) %>
          <%= opcion_menu "Árbol de presuntos responsables",
            sivel2_gen.arbol_presponsables_path, desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu 'Iniciar Sesión', main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  Datos de <a href='http://asomcauca.org/'>ASOM</a><br>
  Sistema de información con fuentes de 
  <a href='https://github.com/pasosdeJesus/si_asom/'>código abierto</a> 
  desarrollado por <a href='http://www.pasosdeJesus.org' target='_blank'>Pasos de Jesús</a>. 2023. 
  </span></p>
<% end %>

<%= render template: 'layouts/msip/application' %>

app/views/msip/hogar/acercade.html.erb
<article>
  <h1>Acerca de</h1>
  <p> El Sistema de Información de ASOM (SI-ASOM) es una aplicación 
  web que se basa en:</p>
  <ul>
    <li>Cor1440:  planeación y seguimiento de proyectos y actividades en una 
      ONG.</li>
    <li>SIVeL2:  manejo de casos de violencia socio política.</li>
  </ul>
<p>Este sistema de información de
<a href="http://www.pasosdeJesus.org/dominio_publico_colombia.html" target="_blank">dominio público de acuerdo a la legislación Colombiana</a>, 
ha sido desarrollado por 
<a href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>.
</p>
</article>

app/views/usuarios/_filtro_habilitado.html.erb
<%= f.input :bushabilitado,
  collection: ['SI', 'NO', 'Todos'],
  label: false,
  selected: Msip::ModeloHelper.poromision(params, :bushabilitado),
  input_html: {
    class: 'tom-select',
    'data-enviarautomatico' => '',
    value: params && params[:filtro] && params[:filtro][:habilitado] ? 
      params[:filtro][:habilitado] : 'SI'
  },
  include_blank: false
%>